### ISSUE TITLE
[BUG:API] 降噪参数开启后，声音不对了

### ISSUE THREAD

**Issue by tuxiaoseng** [lenML/ChatTTS-Forge#103]
### 阅读 README.md 和 dependencies.md

- [X] 我已经阅读过 README.md 和 dependencies.md 文件

### 检索 issue 和 discussion

- [X] 我已经确认之前没有 issue 或 discussion 涉及此 BUG

### 检查 Forge 版本

- [X] 我已经确认问题发生在最新代码或稳定版本中

### Forge Commit 或者 Tag

1

### Python 版本

1

### PyTorch 版本

1

### 操作系统信息

linux

### BUG 描述

开启降噪后声音异常

### BUG 端点

开启降噪后声音异常

### 复现参数

开启降噪后声音异常

### 期望结果

开启降噪后声音异常

### 实际结果

开启降噪后声音异常

### 错误信息

```shell
无错误
```

**Comment by zhzLuke96** [comment]
至少得提供 代码版本/复现参数/操作系统
不然难以复现

**Comment by tuxiaoseng** [comment]
/v1/tts?text={0}&style=narration-professional&spk=Bob&temperature=0.1&top_p=0.7&top_k=20&seed=42&format=mp3&bs=12&thr=100&eos=%5Blbreak%5D&enhance=false&denoise=true&speed=1&pitch=0&volume_gain=0&stream=false

**Comment by tuxiaoseng** [comment]
7月14日更新后出现的问题，api任意问题提交都会有问题。

**Comment by zhzLuke96** [comment]
感谢反馈

fixed f7312c11cd8e3d156dbff62367fa725d95aeaa94
