### ISSUE TITLE
ValueError: mutable default <class 'modules.core.handler.datacls.chattts_model.ChatTTSConfig'> for field tts_config is not allowed: use default_factory[BUG:API] 

### ISSUE THREAD

**Issue by panpan123456** [lenML/ChatTTS-Forge#106]
### 阅读 README.md 和 dependencies.md

- [X] 我已经阅读过 README.md 和 dependencies.md 文件

### 检索 issue 和 discussion

- [X] 我已经确认之前没有 issue 或 discussion 涉及此 BUG

### 检查 Forge 版本

- [X] 我已经确认问题发生在最新代码或稳定版本中

### Forge Commit 或者 Tag

1

### Python 版本

Python 3.11.9

### PyTorch 版本

2.3.1

### 操作系统信息

macos和linux都报同样的问题

### BUG 描述

@dataclass(repr=False, eq=False)
class TTSPipelineContext:
    text: Optional[str] = None
    ssml: Optional[str] = None

    spk: Optional[TTSSpeaker] = None
    tts_config: ChatTTSConfig = ChatTTSConfig()
    infer_config: InferConfig = InferConfig()
    adjust_config: AdjustConfig = AdjustConfig()
    enhancer_config: EnhancerConfig = EnhancerConfig()

    tn_config: TNConfig = TNConfig()

    stop: bool = False

这个pipline会报错ValueError: mutable default <class 'modules.core.handler.datacls.chattts_model.ChatTTSConfig'> for field tts_config is not allowed: use default_factory

### BUG 端点

启动不起来

### 复现参数

python launch.py

### 期望结果

运行成功

### 实际结果

报错ValueError: mutable default <class 'modules.core.handler.datacls.chattts_model.ChatTTSConfig'> for field tts_config is not allowed: use default_factory

### 错误信息

```shell
ValueError: mutable default <class 'modules.core.handler.datacls.chattts_model.ChatTTSConfig'> for field tts_config is not allowed: use default_factory
```

**Comment by zhzLuke96** [comment]
fixed https://github.com/lenML/ChatTTS-Forge/commit/8f4d8b6653b7870495f1be6b19fa9d771b89780c
