### ISSUE TITLE
linux tts_stream返回结果为空[BUG:API] 

### ISSUE THREAD

**Issue by panpan123456** [lenML/ChatTTS-Forge#108]
### 阅读 README.md 和 dependencies.md

- [X] 我已经阅读过 README.md 和 dependencies.md 文件

### 检索 issue 和 discussion

- [X] 我已经确认之前没有 issue 或 discussion 涉及此 BUG

### 检查 Forge 版本

- [X] 我已经确认问题发生在最新代码或稳定版本中

### Forge Commit 或者 Tag

1

### Python 版本

3.11

### PyTorch 版本

2.3.1

### 操作系统信息

linux

### BUG 描述

ip/v1/xtts_v2/tts_stream?text=医学问题向来很严谨&speaker_wav=86facdf85d5447daacb30335fa817840&language=zh
返回的结果是空

### BUG 端点

tts_stream

### 复现参数

text=医学问题向来很严谨&speaker_wav=86facdf85d5447daacb30335fa817840&language=zh

### 期望结果

有音频或者数据

### 实际结果

空

### 错误信息

```shell
无错误日志
```

**Comment by zhzLuke96** [comment]
fixed https://github.com/lenML/ChatTTS-Forge/commit/3613d0db54e692c6dfbfe7697be2411b7e8ef7f9
