### ISSUE TITLE
[ISSUE] 关于开启--compile之后，webui输出窗口乱码以及api后台卡主

### ISSUE THREAD

**Issue by kedgelee** [lenML/ChatTTS-Forge#110]
### 确认清单

- [X] 我已经阅读过 README.md 和 dependencies.md 文件
- [X] 我已经确认之前没有 issue 或 discussion 涉及此 BUG
- [X] 我已经确认问题发生在最新代码或稳定版本中
- [X] 我已经确认问题与 API 无关
- [X] 我已经确认问题与 WebUI 无关
- [X] 我已经确认问题与 Finetune 无关

### 你的issues

你好！我在最新代码中只要webui.py添加--compile启动之后执行推理会出现乱码并卡死，且无任何报错。
version: [v0.7.0-50-gd57c97d](https://github.com/lenML/ChatTTS-Forge/commit/d57c97d681e7dcce0667565d1356832267d4bee7) | branch: main | python: 3.10.14 | torch: 2.3.1 | ffmpeg: 4.3
![image](https://github.com/user-attachments/assets/1456b2d3-b405-4130-a403-e938342d7ef0)

以及launch.py添加--compile启动之后，调用v1/xtts_v2/tts_stream或v1/tts接口开启流式选项都会在完成第一次推理之后服务端就会卡主无法继续执行推理，后台无任何报错。
我是执行的python脚本来测试接口的，在终端会一直显示脚本正在执行的状态，无法通过ctrl+c中断，我试了/docs的文档页面只能中断api服务。
![image](https://github.com/user-attachments/assets/a38a3efa-b83b-4239-a961-9d5b59dbaa53)

我再次使用两周前自己保存的仓库代码（具体版本看不到了）启动webui.py --compile后执行推理会出现同样乱码卡死的情况，但是启动launch.py --compile测试接口并不会出现卡死，可以持续调用接口。

**Comment by zhzLuke96** [comment]
主要是 gradio track 导致的，所以如果你需要在 webui 里开启 compile 的话，那么需要使用下面两个参数（任意一个）

- `--off_tqdm`: 彻底关闭所有 tqdm 进度条
- `--off_track_tqdm`: 关闭 webui 中对于 tqdm 进度条的追踪，关闭之后不会实时同步状态到webui，但是可以在terminal里看
> 推荐用 `--off_track_tqdm` 

added https://github.com/lenML/ChatTTS-Forge/commit/e57b37cd1884afcbf0c939b275e8177200ebb4e1
