### ISSUE TITLE
Support for One-Shot Voice Cloning and vLLM Integration in ChatTTS-Forge

### ISSUE THREAD

**Issue by IrisSally** [lenML/ChatTTS-Forge#111]
### 确认清单

- [X] 我已经仔细阅读[项目文档](https://github.com/lenML/ChatTTS-Forge/blob/master/README.md)，确认现有功能无法解决我的需求
- [X] 我已经检索过现有[issue](https://github.com/lenML/ChatTTS-Forge/issues)，确认与现有issue的内容并不重复
- [X] 确认并非问题讨论而是 Feature request

### 功能描述

With the recent official release of one-shot voice cloning by ChatTTS, the results have been incredibly impressive. Additionally, the community has provided a vLLM version in the dev branch, which has significantly improved inference speed. These advancements could greatly enhance the capabilities of ChatTTS-Forge.

**Feature Request:**

1. **One-Shot Voice Cloning:**
   - Integrate the recently released one-shot voice cloning feature from ChatTTS.
   - Ensure that the implementation maintains the high-quality results demonstrated in the official release.

2. **VLLM Integration:**
   - Incorporate the vLLM version provided by the community in the dev branch.
   - Focus on leveraging the improved inference speed to enhance overall performance.

**Benefits:**

- **Enhanced User Experience:** Users will benefit from the ability to clone voices with just one sample, making the tool more versatile and user-friendly.
- **Improved Performance:** The integration of vLLM will lead to faster inference times, improving the efficiency and responsiveness of the system.

Thank you for considering this feature request. The integration of these advancements will significantly enhance the capabilities and user experience of ChatTTS-Forge.

**Comment by zhzLuke96** [comment]
thx feedback

- 无法集成 chattts 克隆：由于目前 clone 模型没有开源，所以无法集成到 forge 中，不够支持音色导入还是可以做到的
- #113
- #112

**Comment by IrisSally** [comment]
2noise-ChatTTS官方已开源Open-source DVAE encoder and zero shot inferring code.

https://github.com/2noise/ChatTTS/commit/6f4ceb9d46b1155ac9368a3be06c7917710e55e9

**Comment by IrisSally** [comment]
![image](https://github.com/user-attachments/assets/b9f7ed96-d43a-4bf4-8239-75778a0031fb)

**Comment by xiaozhu1106** [comment]
希望能支持，感谢

**Comment by zhzLuke96** [comment]
update

- ChatTTS One-Shot 已支持，详细见 #113 #118
- vllm 部分暂时延期，官方代码还不完善，等后续完善后再接入 #112
