### ISSUE TITLE
[Plan] support ChatTTS zero shot infer

### ISSUE THREAD

**Issue by zhzLuke96** [lenML/ChatTTS-Forge#113]
~~实现导入脚本，以支持将克隆音色导入 forge 中~~
~~ref: https://github.com/2noise/ChatTTS/issues/369~~

# TODOs
- [x] sync upstream code
- [x] 支持 ChatTTS 推理使用 sample audio

**Comment by IrisSally** [comment]
2noise-ChatTTS官方已开源Open-source DVAE encoder and zero shot inferring code.

https://github.com/2noise/ChatTTS/commit/6f4ceb9d46b1155ac9368a3be06c7917710e55e9

**Comment by IrisSally** [comment]
![image](https://github.com/user-attachments/assets/08e5feef-7213-4d87-a936-66d4fd22400d)

**Comment by zhzLuke96** [comment]
added https://github.com/lenML/ChatTTS-Forge/commit/ff4991e0131ab38a929815dedbfbaf1e5b8f854a

相关讨论 https://github.com/lenML/ChatTTS-Forge/discussions/118
