### ISSUE TITLE
[ISSUE] 优化文本产生乱码

### ISSUE THREAD

**Issue by ahkimkoo** [lenML/ChatTTS-Forge#117]
### 确认清单

- [X] 我已经阅读过 README.md 和 dependencies.md 文件
- [X] 我已经确认之前没有 issue 或 discussion 涉及此 BUG
- [X] 我已经确认问题发生在最新代码或稳定版本中
- [X] 我已经确认问题与 API 无关
- [X] 我已经确认问题与 WebUI 无关
- [X] 我已经确认问题与 Finetune 无关

### 你的issues

优化文本产生乱码
![ChatTTS-Forge-WebUI](https://github.com/user-attachments/assets/153d1d36-abd9-427d-81a7-6e09b891c284)
![ChatTTS-Forge-WebUI (1)](https://github.com/user-attachments/assets/10c6c06e-d796-42c6-878f-47540e518f0f)

**Comment by ahkimkoo** [comment]
5d4bafc6e17c1f124f606159655b127a0870b942
这个提交导致的

**Comment by ahkimkoo** [comment]
5d4bafc6e17c1f124f606159655b127a0870b942

这个提交导致的

**Comment by zhzLuke96** [comment]
fixed https://github.com/lenML/ChatTTS-Forge/commit/f0c26024b150859c75d39b1e93b90068fcf2362c
