### ISSUE TITLE
window 使用错误[ISSUE] 

### ISSUE THREAD

**Issue by wtjwrold** [lenML/ChatTTS-Forge#129]
### 确认清单

- [X] 我已经阅读过 README.md 和 dependencies.md 文件
- [X] 我已经确认之前没有 issue 或 discussion 涉及此 BUG
- [X] 我已经确认问题发生在最新代码或稳定版本中
- [X] 我已经确认问题与 API 无关
- [X] 我已经确认问题与 WebUI 无关
- [X] 我已经确认问题与 Finetune 无关

### 你的issues

![202408051](https://github.com/user-attachments/assets/53ebb8dc-36a3-4a80-97ed-48b2aa24ae47)
![8D163B4D-E20D-4c74-A368-FED5470E3823](https://github.com/user-attachments/assets/737a0ee7-01a7-4a40-9269-886bcdd3ca22)
本地
window 系统
处理器：13th Gen Intel(R) Core(TM) i7-1370P   1.90 GHz

**Comment by zhzLuke96** [comment]
报错信息不完整，难以定位问题，你可以把完整的报错信息文本复制过来吗，或者简单说一下怎么操作会报错
