### ISSUE TITLE
[BUG:WebUI] 生成的spk和参考音频不符

### ISSUE THREAD

**Issue by tuxiaoseng** [lenML/ChatTTS-Forge#133]
### 确认清单

- [X] 我已经阅读过 README.md 和 dependencies.md 文件
- [X] 我已经确认之前没有 issue 或 discussion 涉及此 BUG
- [X] 我已经确认问题发生在最新代码或稳定版本中

### Forge Commit 或者 Tag

26d9b0edcf15b074d36c31a0f226769b60a26676

### Python 版本

3.10.8

### PyTorch 版本

2.3.1

### 操作系统信息

linux

### BUG 描述

[tiandao.spkv1.json](https://github.com/user-attachments/files/16569053/tiandao.spkv1.json)
带有参考音频的spk测试声音发现胡言论语，音色不匹配
text：chat T T S 是一款强大的对话式文本转语音模型。它有中英混读和多说话人的能力。
参考音频：

https://github.com/user-attachments/assets/66edace5-edea-4d7d-817c-d2dde65db892

### 复现步骤

<img width="1011" alt="微信图片_20240810172551" src="https://github.com/user-attachments/assets/067e934e-74f1-4c95-ace9-3016364ecbd1">

### 期望结果

正常

### 实际结果

异常

**Comment by zhzLuke96** [comment]
感谢反馈

这个问题有点复杂
- 一个是你创建的这个 spk 文件有点不太对，里面解析的数据有点问题，采样率不对
- 另一个问题是 ChatTTS 模型的问题，ref text 需要有 eos，不然模型推理的时候容易有问题。简单说就是参考文本句尾最好是 `"。"` 句号。

建议
首先，你看看你本地的 gradio 版本是否是最新的，尝试更新一下gradio版本
其次，我给你修复了一个 spk 文件，你可以参考这个再调试下看看
[tmpjd0wdkxi.spkv1.json](https://github.com/user-attachments/files/16569289/tmpjd0wdkxi.spkv1.json)

如果还有问题的话继续提供信息，这一块代码刚加，测试还不太完善

**Comment by tuxiaoseng** [comment]
gradio升级到最新的4.41，使用了带句号的参考文本，在webui下新建spk还是有这样的问题，[版本也更新到最新了](3ab5d3fe23d36ac1313b8891ac4b19ba971b1b97)

**Comment by zhzLuke96** [comment]
还需要更多信息，不好定位是什么问题

taindao_0001.mp4 这个文件应该是转码过的吧？源文件是 mp3/wav/flac 之类的？
可以提供一份你用来创建的spk的音频源文件吗？我怀疑有可能是处理不同音频文件的时候有什么bug，得有你的原文件才好排查

**Comment by zhzLuke96** [comment]
可能相关 https://github.com/2noise/ChatTTS/issues/648

**Comment by zhzLuke96** [comment]
fixed 1047efad4192b949e25cfb7f8a8bb88282a79518

应该在这个 commit 修复了
