### ISSUE TITLE
Support FishSpeech SFT version

### ISSUE THREAD

**Issue by zhzLuke96** [lenML/ChatTTS-Forge#135]

**Comment by zhzLuke96** [comment]
ref https://github.com/lenML/ChatTTS-Forge/issues/90#issuecomment-2230984786

**Comment by tuxiaoseng** [comment]
fishspeech1.2效果还是很好的，除了偶尔的吞字，推理速度很快效果很好，希望能尽快更新

**Comment by zhzLuke96** [comment]
done.

NOTE: 测试的时候发现模型生成时不时会有一小段重复，不清楚是哪部分的问题...
