### ISSUE TITLE
[BUG:WebUI] ASR 操作报错 Error: libcudnn_ops_infer.so.8

### ISSUE THREAD

**Issue by cpken** [lenML/ChatTTS-Forge#139]
### 确认清单

- [X] 我已经阅读过 README.md 和 dependencies.md 文件
- [X] 我已经确认之前没有 issue 或 discussion 涉及此 BUG
- [X] 我已经确认问题发生在最新代码或稳定版本中

### Forge Commit 或者 Tag

无

### Python 版本

无

### PyTorch 版本

无

### 操作系统信息

无

### BUG 描述

python: 3.10.14 | torch: 2.4.0+cu121 | ffmpeg: 4.2.7-0ubuntu0.1
模型来源：https://huggingface.co/Systran/faster-whisper-large-v3

```
2024-08-15 18:18:01,246 - modules.core.models.stt.Whisper - INFO - Whisper model loaded.
2024-08-15 18:18:01,246 - faster_whisper - INFO - Processing audio with duration 00:20.434
Could not load library libcudnn_ops_infer.so.8. Error: libcudnn_ops_infer.so.8: cannot open shared object file: No such file or directory
已放弃 (核心已转储)
```

### 复现步骤

执行 ASR 操作

### 期望结果

无

### 实际结果

无

**Comment by zhzLuke96** [comment]
看起来是环境配置问题和本库无关，没有特别情况的话不会对这个问题做代码修复

建议
参考这几个 issues 自行解决
- https://github.com/RVC-Boss/GPT-SoVITS/issues/1071#issuecomment-2112439286
- https://github.com/SYSTRAN/faster-whisper/issues/516#issuecomment-1972615012
- https://github.com/RVC-Boss/GPT-SoVITS/issues/697#issuecomment-2219681374
- https://github.com/jianchang512/stt/issues/7#issuecomment-1913577983
- https://github.com/RVC-Boss/GPT-SoVITS/issues/1071#issuecomment-2112439286


> 注释：貌似是很常见的问题，所以这个issue暂时不会关闭

**Comment by cpken** [comment]
暂无参看用途，可能是因为版本的问题。我的版本是目前 cuda 最新的稳定版。
