### ISSUE TITLE
[ISSUE] the docker config is broken

### ISSUE THREAD

**Issue by highkay** [lenML/ChatTTS-Forge#161]
### 确认清单

- [X] 我已经阅读过 README.md 和 dependencies.md 文件
- [X] 我已经确认之前没有 issue 或 discussion 涉及此 BUG
- [X] 我已经确认问题发生在最新代码或稳定版本中
- [X] 我已经确认问题与 API 无关
- [X] 我已经确认问题与 WebUI 无关
- [X] 我已经确认问题与 Finetune 无关

### 你的issues

The base image in Dockerfile is pytorch/serve, which latest python version is 3.9. The dependencies and the source code depend on 3.10, suggest replacing the base image with https://github.com/fabridamicelli/torchserve-docker.

**Comment by zhzLuke96** [comment]
fixed https://github.com/lenML/ChatTTS-Forge/commit/e56b2d8e1774b75e4f2691f4782e01c585a7a30c
