### ISSUE TITLE
加一个保存音色.pt功能？

### ISSUE THREAD

**Issue by 40740** [lenML/ChatTTS-Forge#18]
很棒的项目哦，感谢付出。请问可以加一个保存音色的功能吗？要不然用种子，下次重启启动，种子的音色也是不一样的欸。谢谢宝。

**Comment by zhzLuke96** [comment]
- 对于webui

很巧，刚刚推送了新功能，webui中可以合并 speaker 和 上传 spaker.pt

不过单独保存特定种子 speaker 的功能还没有，可以先尝试 merge


- 对于 api

如果你是通过api服务使用 forge的话，启动 api 服务之后，可以到 playground 中创建 speaker

**Comment by 40740** [comment]
耶~我的api 一直测试有问题，更新你刚刚的版本。

`PS G:\AI\ChatTTS\new\ChatTTS-Forge-main> python launch.py --compile
Traceback (most recent call last):
  File "G:\AI\ChatTTS\new\ChatTTS-Forge-main\launch.py", line 11, in <module>
    from modules import generate_audio as generate
  File "G:\AI\ChatTTS\new\ChatTTS-Forge-main\modules\generate_audio.py", line 4, in <module>
    from modules.speaker import Speaker
  File "G:\AI\ChatTTS\new\ChatTTS-Forge-main\modules\speaker.py", line 3, in <module>
    from box import Box
ModuleNotFoundError: No module named 'box'`

然后 resemble-enhance 这个模块 安装不成功。windows11 安装这个好像蛮困难的

**Comment by zhzLuke96** [comment]
那个库确实有点问题，现在最新的代码不依赖了，可以拉最新的试下

**Comment by zhzLuke96** [comment]
保存pt功能已实现，此issue关闭 df265490f35b2b991c395455dd2f4ad563193cef
