### ISSUE TITLE
无法安装依赖'resemble-enhance'

### ISSUE THREAD

**Issue by alex9441** [lenML/ChatTTS-Forge#19]
错误日志如下:
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      test.c
      LINK : fatal error LNK1181: 无法打开输入文件“aio.lib”
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\embra\AppData\Local\Temp\pip-install-ge4atg9m\deepspeed_a86ec1095150421b9182b476bcffcf33\setup.py", line 182, in <module>
          abort(f"Unable to pre-compile {op_name}")
        File "C:\Users\embra\AppData\Local\Temp\pip-install-ge4atg9m\deepspeed_a86ec1095150421b9182b476bcffcf33\setup.py", line 52, in abort
          assert False, msg
      AssertionError: Unable to pre-compile async_io
      DS_BUILD_OPS=1
       [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
       [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
       [WARNING]  One can disable async_io with DS_BUILD_AIO=0
       [ERROR]  Unable to pre-compile async_io
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

对于Windows用户来说,安装libaio实在太艰难了!求大佬换个姿势吧.

**Comment by zhzLuke96** [comment]
fixed b8f41f90061c75ee3e09ddc6cae8d657bc67aad1 b8f41f90061c75ee3e09ddc6cae8d657bc67aad1
