### ISSUE TITLE
语言问题

### ISSUE THREAD

**Issue by Phrixus2023** [lenML/ChatTTS-Forge#20]
现在界面上的语言不统一，可以统一用英文便于国际传播，然后增加一个类似fooocus的语言文件功能，这样可以自己翻译成其他语言进行界面语言更改，不然界面语言有点乱。然后可以把说明里面的内容附加到每个功能下面以小字方式显示会容易对照着看。
另外webui.py尾部可以增加一行inbrowser=True,这样就可以自动用浏览器打开，节省一步用户操作。

**Comment by zhzLuke96** [comment]
add

f56caa71e9186680b93c487d9645186ae18c1dc6
c05035d5cdcc5aa7efd995fe42f6a2541abe718b
