### ISSUE TITLE
大佬好，开启增强和降噪就会报错。

### ISSUE THREAD

**Issue by fsjoy52** [lenML/ChatTTS-Forge#24]
大佬好，开启增强和降噪就会报错。
```
rompt1': '', 'prompt2': '', 'prefix': ''}
100%|█████████████████████████████████████████████████████████████████████████████| 2048/2048 [00:13<00:00, 151.70it/s]
INFO:modules.repos_static.resemble_enhance.hparams:Reading hparams from D:\AI\ChatTTS-Forge\models\resemble-enhance\hparams.yaml
INFO:modules.repos_static.resemble_enhance.enhancer.lcfm.lcfm:Freeze ae (encoder and decoder)
Traceback (most recent call last):
  File "D:\AI\anaconda3\envs\ChatTTS_Forge\lib\site-packages\gradio\queueing.py", line 532, in process_events
    response = await route_utils.call_process_api(
  File "D:\AI\anaconda3\envs\ChatTTS_Forge\lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\AI\anaconda3\envs\ChatTTS_Forge\lib\site-packages\gradio\blocks.py", line 1928, in process_api
    result = await self.call_function(
  File "D:\AI\anaconda3\envs\ChatTTS_Forge\lib\site-packages\gradio\blocks.py", line 1514, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\AI\anaconda3\envs\ChatTTS_Forge\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "D:\AI\anaconda3\envs\ChatTTS_Forge\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "D:\AI\anaconda3\envs\ChatTTS_Forge\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "D:\AI\anaconda3\envs\ChatTTS_Forge\lib\site-packages\gradio\utils.py", line 832, in wrapper
    response = f(*args, **kwargs)
  File "D:\AI\ChatTTS-Forge\modules\webui\webui_utils.py", line 221, in tts_generate
    audio_data, sample_rate = apply_audio_enhance(
  File "D:\AI\anaconda3\envs\ChatTTS_Forge\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\AI\ChatTTS-Forge\modules\webui\webui_utils.py", line 94, in apply_audio_enhance
    enhancer = load_enhancer(device)
  File "D:\AI\ChatTTS-Forge\modules\Enhancer\ResembleEnhance.py", line 24, in load_enhancer
    resemble_enhance.load_model()
  File "D:\AI\ChatTTS-Forge\modules\Enhancer\ResembleEnhance.py", line 38, in load_model
    state_dict = torch.load(
  File "D:\AI\anaconda3\envs\ChatTTS_Forge\lib\site-packages\torch\serialization.py", line 997, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "D:\AI\anaconda3\envs\ChatTTS_Forge\lib\site-packages\torch\serialization.py", line 444, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "D:\AI\anaconda3\envs\ChatTTS_Forge\lib\site-packages\torch\serialization.py", line 425, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\AI\\ChatTTS-Forge\\models\\resemble-enhance\\mp_rank_00_model_states.pt'
```
以上是开启增强的报错
下面是开启降噪的报错。不开启增强和降噪就不会报错。
```
(ChatTTS_Forge) D:\AI\ChatTTS-Forge>python webui.py
INFO:modules.webui.app:WebUI module initialized
INFO:modules.webui.localization:Loaded localization file D:\AI\ChatTTS-Forge\language\zh-CN.json
INFO:modules.generate_audio:LRU cache enabled with size 64
INFO:modules.devices.devices:Using full precision: torch.float32
INFO:modules.devices.devices:Using device: cuda
Running on local URL:  http://0.0.0.0:7860
INFO:httpx:HTTP Request: GET https://api.gradio.app/pkg-version "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: GET https://checkip.amazonaws.com/ "HTTP/1.1 200 "
INFO:httpx:HTTP Request: GET http://localhost:7860/startup-events "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD http://localhost:7860/ "HTTP/1.1 200 OK"

To create a public link, set `share=True` in `launch()`.
INFO:modules.models:Loading ChatTTS models
INFO:modules.ChatTTS.ChatTTS.core:Load from local: ./models/ChatTTS
INFO:modules.ChatTTS.ChatTTS.core:vocos loaded.
INFO:modules.ChatTTS.ChatTTS.core:dvae loaded.
INFO:modules.ChatTTS.ChatTTS.core:gpt loaded.
INFO:modules.ChatTTS.ChatTTS.core:decoder loaded.
INFO:modules.ChatTTS.ChatTTS.core:tokenizer loaded.
INFO:modules.ChatTTS.ChatTTS.core:All initialized.
INFO:modules.models:ChatTTS models loaded
INFO:modules.generate_audio:('spk', 'female2')
INFO:modules.generate_audio:{'text': ['chat T T S 是一款强大的对话式文本转语音模型。它有中英混读和多说话人的能力。'], 'infer_seed': 42, 'temperature': 0.3, 'top_P': 0.7, 'top_K': 20, 'prompt1': '', 'prompt2': '', 'prefix': ''}
  0%|                                                                                         | 0/2048 [00:00<?, ?it/s]D:\AI\anaconda3\envs\ChatTTS_Forge\lib\site-packages\transformers\models\llama\modeling_llama.py:649: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:455.)
  attn_output = torch.nn.functional.scaled_dot_product_attention(
100%|█████████████████████████████████████████████████████████████████████████████| 2048/2048 [00:11<00:00, 177.40it/s]
INFO:modules.repos_static.resemble_enhance.hparams:Reading hparams from D:\AI\ChatTTS-Forge\models\resemble-enhance\hparams.yaml
INFO:modules.repos_static.resemble_enhance.enhancer.lcfm.lcfm:Freeze ae (encoder and decoder)
Traceback (most recent call last):
  File "D:\AI\anaconda3\envs\ChatTTS_Forge\lib\site-packages\gradio\queueing.py", line 532, in process_events
    response = await route_utils.call_process_api(
  File "D:\AI\anaconda3\envs\ChatTTS_Forge\lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\AI\anaconda3\envs\ChatTTS_Forge\lib\site-packages\gradio\blocks.py", line 1928, in process_api
    result = await self.call_function(
  File "D:\AI\anaconda3\envs\ChatTTS_Forge\lib\site-packages\gradio\blocks.py", line 1514, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\AI\anaconda3\envs\ChatTTS_Forge\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "D:\AI\anaconda3\envs\ChatTTS_Forge\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "D:\AI\anaconda3\envs\ChatTTS_Forge\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "D:\AI\anaconda3\envs\ChatTTS_Forge\lib\site-packages\gradio\utils.py", line 832, in wrapper
    response = f(*args, **kwargs)
  File "D:\AI\ChatTTS-Forge\modules\webui\webui_utils.py", line 221, in tts_generate
    audio_data, sample_rate = apply_audio_enhance(
  File "D:\AI\anaconda3\envs\ChatTTS_Forge\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\AI\ChatTTS-Forge\modules\webui\webui_utils.py", line 94, in apply_audio_enhance
    enhancer = load_enhancer(device)
  File "D:\AI\ChatTTS-Forge\modules\Enhancer\ResembleEnhance.py", line 24, in load_enhancer
    resemble_enhance.load_model()
  File "D:\AI\ChatTTS-Forge\modules\Enhancer\ResembleEnhance.py", line 38, in load_model
    state_dict = torch.load(
  File "D:\AI\anaconda3\envs\ChatTTS_Forge\lib\site-packages\torch\serialization.py", line 997, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "D:\AI\anaconda3\envs\ChatTTS_Forge\lib\site-packages\torch\serialization.py", line 444, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "D:\AI\anaconda3\envs\ChatTTS_Forge\lib\site-packages\torch\serialization.py", line 425, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\AI\\ChatTTS-Forge\\models\\resemble-enhance\\mp_rank_00_model_states.pt'
```
看着是缺少模型，但是没看到哪里有这俩模型下载。

**Comment by fsjoy52** [comment]
好像都是报的同一个错哈。-。-小白不太懂。就是折腾折腾

**Comment by zhzLuke96** [comment]
原因是缺少模型

在项目目录下执行这个下载模型即可： `python -m scripts/download_models --source modelscope`

**Comment by hotdogarea** [comment]
> 大佬好，开启增强和降噪就会报错。
> 
> ```
> rompt1': '', 'prompt2': '', 'prefix': ''}
> 100%|█████████████████████████████████████████████████████████████████████████████| 2048/2048 [00:13<00:00, 151.70it/s]
> INFO:modules.repos_static.resemble_enhance.hparams:Reading hparams from D:\AI\ChatTTS-Forge\models\resemble-enhance\hparams.yaml
> INFO:modules.repos_static.resemble_enhance.enhancer.lcfm.lcfm:Freeze ae (encoder and decoder)
> Traceback (most recent call last):
>   File "D:\AI\anaconda3\envs\ChatTTS_Forge\lib\site-packages\gradio\queueing.py", line 532, in process_events
>     response = await route_utils.call_process_api(
>   File "D:\AI\anaconda3\envs\ChatTTS_Forge\lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
>     output = await app.get_blocks().process_api(
>   File "D:\AI\anaconda3\envs\ChatTTS_Forge\lib\site-packages\gradio\blocks.py", line 1928, in process_api
>     result = await self.call_function(
>   File "D:\AI\anaconda3\envs\ChatTTS_Forge\lib\site-packages\gradio\blocks.py", line 1514, in call_function
>     prediction = await anyio.to_thread.run_sync(
>   File "D:\AI\anaconda3\envs\ChatTTS_Forge\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
>     return await get_async_backend().run_sync_in_worker_thread(
>   File "D:\AI\anaconda3\envs\ChatTTS_Forge\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
>     return await future
>   File "D:\AI\anaconda3\envs\ChatTTS_Forge\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
>     result = context.run(func, *args)
>   File "D:\AI\anaconda3\envs\ChatTTS_Forge\lib\site-packages\gradio\utils.py", line 832, in wrapper
>     response = f(*args, **kwargs)
>   File "D:\AI\ChatTTS-Forge\modules\webui\webui_utils.py", line 221, in tts_generate
>     audio_data, sample_rate = apply_audio_enhance(
>   File "D:\AI\anaconda3\envs\ChatTTS_Forge\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
>     return func(*args, **kwargs)
>   File "D:\AI\ChatTTS-Forge\modules\webui\webui_utils.py", line 94, in apply_audio_enhance
>     enhancer = load_enhancer(device)
>   File "D:\AI\ChatTTS-Forge\modules\Enhancer\ResembleEnhance.py", line 24, in load_enhancer
>     resemble_enhance.load_model()
>   File "D:\AI\ChatTTS-Forge\modules\Enhancer\ResembleEnhance.py", line 38, in load_model
>     state_dict = torch.load(
>   File "D:\AI\anaconda3\envs\ChatTTS_Forge\lib\site-packages\torch\serialization.py", line 997, in load
>     with _open_file_like(f, 'rb') as opened_file:
>   File "D:\AI\anaconda3\envs\ChatTTS_Forge\lib\site-packages\torch\serialization.py", line 444, in _open_file_like
>     return _open_file(name_or_buffer, mode)
>   File "D:\AI\anaconda3\envs\ChatTTS_Forge\lib\site-packages\torch\serialization.py", line 425, in __init__
>     super().__init__(open(name, mode))
> FileNotFoundError: [Errno 2] No such file or directory: 'D:\\AI\\ChatTTS-Forge\\models\\resemble-enhance\\mp_rank_00_model_states.pt'
> ```
> 
> 以上是开启增强的报错 下面是开启降噪的报错。不开启增强和降噪就不会报错。
> 
> ```
> (ChatTTS_Forge) D:\AI\ChatTTS-Forge>python webui.py
> INFO:modules.webui.app:WebUI module initialized
> INFO:modules.webui.localization:Loaded localization file D:\AI\ChatTTS-Forge\language\zh-CN.json
> INFO:modules.generate_audio:LRU cache enabled with size 64
> INFO:modules.devices.devices:Using full precision: torch.float32
> INFO:modules.devices.devices:Using device: cuda
> Running on local URL:  http://0.0.0.0:7860
> INFO:httpx:HTTP Request: GET https://api.gradio.app/pkg-version "HTTP/1.1 200 OK"
> INFO:httpx:HTTP Request: GET https://checkip.amazonaws.com/ "HTTP/1.1 200 "
> INFO:httpx:HTTP Request: GET http://localhost:7860/startup-events "HTTP/1.1 200 OK"
> INFO:httpx:HTTP Request: HEAD http://localhost:7860/ "HTTP/1.1 200 OK"
> 
> To create a public link, set `share=True` in `launch()`.
> INFO:modules.models:Loading ChatTTS models
> INFO:modules.ChatTTS.ChatTTS.core:Load from local: ./models/ChatTTS
> INFO:modules.ChatTTS.ChatTTS.core:vocos loaded.
> INFO:modules.ChatTTS.ChatTTS.core:dvae loaded.
> INFO:modules.ChatTTS.ChatTTS.core:gpt loaded.
> INFO:modules.ChatTTS.ChatTTS.core:decoder loaded.
> INFO:modules.ChatTTS.ChatTTS.core:tokenizer loaded.
> INFO:modules.ChatTTS.ChatTTS.core:All initialized.
> INFO:modules.models:ChatTTS models loaded
> INFO:modules.generate_audio:('spk', 'female2')
> INFO:modules.generate_audio:{'text': ['chat T T S 是一款强大的对话式文本转语音模型。它有中英混读和多说话人的能力。'], 'infer_seed': 42, 'temperature': 0.3, 'top_P': 0.7, 'top_K': 20, 'prompt1': '', 'prompt2': '', 'prefix': ''}
>   0%|                                                                                         | 0/2048 [00:00<?, ?it/s]D:\AI\anaconda3\envs\ChatTTS_Forge\lib\site-packages\transformers\models\llama\modeling_llama.py:649: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:455.)
>   attn_output = torch.nn.functional.scaled_dot_product_attention(
> 100%|█████████████████████████████████████████████████████████████████████████████| 2048/2048 [00:11<00:00, 177.40it/s]
> INFO:modules.repos_static.resemble_enhance.hparams:Reading hparams from D:\AI\ChatTTS-Forge\models\resemble-enhance\hparams.yaml
> INFO:modules.repos_static.resemble_enhance.enhancer.lcfm.lcfm:Freeze ae (encoder and decoder)
> Traceback (most recent call last):
>   File "D:\AI\anaconda3\envs\ChatTTS_Forge\lib\site-packages\gradio\queueing.py", line 532, in process_events
>     response = await route_utils.call_process_api(
>   File "D:\AI\anaconda3\envs\ChatTTS_Forge\lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
>     output = await app.get_blocks().process_api(
>   File "D:\AI\anaconda3\envs\ChatTTS_Forge\lib\site-packages\gradio\blocks.py", line 1928, in process_api
>     result = await self.call_function(
>   File "D:\AI\anaconda3\envs\ChatTTS_Forge\lib\site-packages\gradio\blocks.py", line 1514, in call_function
>     prediction = await anyio.to_thread.run_sync(
>   File "D:\AI\anaconda3\envs\ChatTTS_Forge\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
>     return await get_async_backend().run_sync_in_worker_thread(
>   File "D:\AI\anaconda3\envs\ChatTTS_Forge\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
>     return await future
>   File "D:\AI\anaconda3\envs\ChatTTS_Forge\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
>     result = context.run(func, *args)
>   File "D:\AI\anaconda3\envs\ChatTTS_Forge\lib\site-packages\gradio\utils.py", line 832, in wrapper
>     response = f(*args, **kwargs)
>   File "D:\AI\ChatTTS-Forge\modules\webui\webui_utils.py", line 221, in tts_generate
>     audio_data, sample_rate = apply_audio_enhance(
>   File "D:\AI\anaconda3\envs\ChatTTS_Forge\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
>     return func(*args, **kwargs)
>   File "D:\AI\ChatTTS-Forge\modules\webui\webui_utils.py", line 94, in apply_audio_enhance
>     enhancer = load_enhancer(device)
>   File "D:\AI\ChatTTS-Forge\modules\Enhancer\ResembleEnhance.py", line 24, in load_enhancer
>     resemble_enhance.load_model()
>   File "D:\AI\ChatTTS-Forge\modules\Enhancer\ResembleEnhance.py", line 38, in load_model
>     state_dict = torch.load(
>   File "D:\AI\anaconda3\envs\ChatTTS_Forge\lib\site-packages\torch\serialization.py", line 997, in load
>     with _open_file_like(f, 'rb') as opened_file:
>   File "D:\AI\anaconda3\envs\ChatTTS_Forge\lib\site-packages\torch\serialization.py", line 444, in _open_file_like
>     return _open_file(name_or_buffer, mode)
>   File "D:\AI\anaconda3\envs\ChatTTS_Forge\lib\site-packages\torch\serialization.py", line 425, in __init__
>     super().__init__(open(name, mode))
> FileNotFoundError: [Errno 2] No such file or directory: 'D:\\AI\\ChatTTS-Forge\\models\\resemble-enhance\\mp_rank_00_model_states.pt'
> ```
> 
> 看着是缺少模型，但是没看到哪里有这俩模型下载。

这个版本推理速度能达到一百七it/s ?  什么显卡啊  显存占用多少？老哥
