### ISSUE TITLE
readme 中docker章节指令有一点书写错误

### ISSUE THREAD

**Issue by Just-blue** [lenML/ChatTTS-Forge#27]
原：
下载模型: python -m scripts/download_models --source huggingface
改正：
 python -m scripts.download_models --source huggingface

原：
webui: docker-compose -f ./docker-cmopose.webui.yml up -d
api: docker-compose -f ./docker-cmopose.api.yml up -d
改正：
webui: docker-compose -f ./docker-compose.webui.yml up -d
api: docker-compose -f ./docker-compose.api.yml up -d

**Comment by zhzLuke96** [comment]
fixed d0ba3b932449a1e229d43817da07fc80d310bb9c
