### ISSUE TITLE
未知原因造成进程频繁结束

### ISSUE THREAD

**Issue by alex9441** [lenML/ChatTTS-Forge#28]
API工作正常,webUI每次切换风格或音色,文本输入新内容都会造成进程结束,日志内也找不到有效的提示.
如下:

2024-06-11 11:54:05,705 - modules.models - INFO - ChatTTS models loaded
2024-06-11 11:54:05,722 - modules.generate_audio - INFO - ('spk', 'female2')
2024-06-11 11:54:05,722 - modules.generate_audio - INFO - {'text': ['公司的年度总结会议将在下周三举行，请各部门提前准备好相关材料，确保会议顺利进行 [lbreak] '], 'infer_seed': 42, 'temperature': 0.3, 'top_P': 0.7, 'top_K': 20, 'prompt1': '', 'prompt2': '', 'prefix': ''}
  0%|          | 0/2048 [00:00<?, ?it/s]C:\Users\embra\.conda\envs\ChatTTS-Forge\Lib\site-packages\transformers\models\llama\modeling_llama.py:649: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:263.)
  attn_output = torch.nn.functional.scaled_dot_product_attention(
100%|██████████| 2048/2048 [00:05<00:00, 395.60it/s]
2024-06-11 11:54:11,176 - modules.repos_static.resemble_enhance.hparams - INFO - Reading hparams from C:\0_AI_0\ChatTTS-Forge\20\models\resemble-enhance\hparams.yaml
2024-06-11 11:54:11,735 - modules.repos_static.resemble_enhance.enhancer.lcfm.lcfm - INFO - Freeze ae (encoder and decoder)
100%|██████████| 1/1 [00:02<00:00,  2.12s/it]
2024-06-11 11:54:15,278 - modules.repos_static.resemble_enhance.inference - INFO - Elapsed time: 2.198 s, 170.603 kHz

进程已结束，退出代码为 0

**Comment by zhzLuke96** [comment]
fixed 3a7cbde6ccdfd20a6c53d7625d4e652007367fbf

**Comment by hotdogarea** [comment]
> API工作正常,webUI每次切换风格或音色,文本输入新内容都会造成进程结束,日志内也找不到有效的提示. 如下:
> 
> 2024-06-11 11:54:05,705 - modules.models - INFO - ChatTTS models loaded2024-06-11 11：54：05,705 - modules.models - 信息 - ChatTTS模型已加载 2024-06-11 11:54:05,722 - modules.generate_audio - INFO - ('spk', 'female2')2024-06-11 11：54：05,722 - modules.generate_audio - 信息 - （'spk'， 'female2'） 2024-06-11 11:54:05,722 - modules.generate_audio - INFO - {'text': ['公司的年度总结会议将在下周三举行，请各部门提前准备好相关材料，确保会议顺利进行 [lbreak] '], 'infer_seed': 42, 'temperature': 0.3, 'top_P': 0.7, 'top_K': 20, 'prompt1': '', 'prompt2': '', 'prefix': ''} 0%| | 0/2048 [00:00<?, ?it/s]C:\Users\embra.conda\envs\ChatTTS-Forge\Lib\site-packages\transformers\models\llama\modeling_llama.py:649: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:263.)0%| |0/2048 [00：00<?, ?it/s]C：\Users\embra.conda\envs\ChatTTS-Forge\Lib\site-packages\transformers\models\llama\modeling_llama.py：649：UserWarning：1Torch 未通过闪光灯进行编译。（在内部触发 ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp：263。 attn_output = torch.nn.functional.scaled_dot_product_attention(attn_output = torch.nn.functional.scaled_dot_product_attention（ 100%|██████████| 2048/2048 [00:05<00:00, 395.60it/s]100%|██████████|2048/2048 [00：05<00：00， 395.60it/s] 2024-06-11 11:54:11,176 - modules.repos_static.resemble_enhance.hparams - INFO - Reading hparams from C:\0_AI_0\ChatTTS-Forge\20\models\resemble-enhance\hparams.yaml2024-06-11 11：54：11,176 - modules.repos_static.resemble_enhance.hparams - 信息 - 从 C：\0_AI_0\ChatTTS-Forge\20\models\resemble-enhance\hparams.yaml 读取 hparams 2024-06-11 11:54:11,735 - modules.repos_static.resemble_enhance.enhancer.lcfm.lcfm - INFO - Freeze ae (encoder and decoder)2024-06-11 11：54：11,735 - modules.repos_static.resemble_enhance.enhancer.lcfm.lcfm - 信息 - 冻结 ae（编码器和解码器） 100%|██████████| 1/1 [00:02<00:00, 2.12s/it]100%|██████████|1/1 [00：02<00：00， 2.12秒/it] 2024-06-11 11:54:15,278 - modules.repos_static.resemble_enhance.inference - INFO - Elapsed time: 2.198 s, 170.603 kHz2024-06-11 11：54：15,278 - modules.repos_static.resemble_enhance.inference - 信息 - 运行时间：2.198 秒，170.603 kHz
> 
> 进程已结束，退出代码为 0
这个版本推理速度能达到近四百it/s???!!
