### ISSUE TITLE
no file mp_rank_00_model_states.pt

### ISSUE THREAD

**Issue by yincangshiwei** [lenML/ChatTTS-Forge#29]
请问mp_rank_00_model_states.pt从哪里下载的，找不到这玩意。

**Comment by Phrixus2023** [comment]
https://modelscope.cn/api/v1/studio/insummer/ResembleEnhance/repo?Revision=master&FilePath=resemble_enhance%2Fmodel_repo%2Fenhancer_stage2%2Fds%2FG%2Fdefault%2Fmp_rank_00_model_states.pt

**Comment by yincangshiwei** [comment]
> https://modelscope.cn/api/v1/studio/insummer/ResembleEnhance/repo?Revision=master&FilePath=resemble_enhance%2Fmodel_repo%2Fenhancer_stage2%2Fds%2FG%2Fdefault%2Fmp_rank_00_model_states.pt

thanks

**Comment by yincangshiwei** [comment]
> > https://modelscope.cn/api/v1/studio/insummer/ResembleEnhance/repo?Revision=master&FilePath=resemble_enhance%2Fmodel_repo%2Fenhancer_stage2%2Fds%2FG%2Fdefault%2Fmp_rank_00_model_states.pt
> 
> thanks

https://huggingface.co/ResembleAI/resemble-enhance/resolve/main/enhancer_stage2/ds/G/default/mp_rank_00_model_states.pt?download=true
