### ISSUE TITLE
启动webui.py运行完自动退出了，最新代码

### ISSUE THREAD

**Issue by yincangshiwei** [lenML/ChatTTS-Forge#30]
如图所示，启动完自动退出了：
![image](https://github.com/lenML/ChatTTS-Forge/assets/8185843/1717e406-e578-4599-93c4-073a5ad048bd)

**Comment by rans0mban** [comment]
是不是提示：python webui.py
fatal: No names found, cannot describe anything.
我也是遇到相同问题，自动结束了

**Comment by zhzLuke96** [comment]
fixed 3a7cbde6ccdfd20a6c53d7625d4e652007367fbf
