### ISSUE TITLE
[ISSUE] --use_cpu 参数并没有在webui.py里

### ISSUE THREAD

**Issue by LuHugo** [lenML/ChatTTS-Forge#47]
### 阅读 README.md 和 dependencies.md

- [X] 我已经阅读过 README.md 和 dependencies.md 文件

### 检索 issue 和 discussion

- [X] 我已经确认之前没有 issue 或 discussion 涉及此 BUG

### 检查 Forge 版本

- [X] 我已经确认问题发生在最新代码或稳定版本中

### 你的issues

启动时加了--use_cpu=“all” 没有任何作用，然后在webui.py文件的代码里并没有看到有接受这个参数

**Comment by zhzLuke96** [comment]
fixed 221962fd0f61d3f269918b26a814cbcd5aabd1f0
