### ISSUE TITLE
[Feature] 希望支持离线整合包 方便使用

### ISSUE THREAD

**Issue by louyongjiu** [lenML/ChatTTS-Forge#60]
### verify

- [X] 我已经仔细阅读[项目文档](https://github.com/lenML/ChatTTS-Forge/blob/master/README.md)，确认现有功能无法解决我的需求
- [X] 我已经检索过现有[issue](https://github.com/lenML/ChatTTS-Forge/issues)，确认与现有issue的内容并不重复
- [X] 确认并非问题讨论而是 Feature request

### 功能描述

希望支持离线整合包 降低门槛 方便使用

### 可能的解决方案

类似项目ChatTTS_colab 提供了离线整合包 可以参考
https://github.com/6drf21e/ChatTTS_colab

**Comment by Phrixus2023** [comment]
我做了一个，链接：https://pan.baidu.com/s/1ZBv6rC9A2P1OwQ2VPDpdzw?pwd=8xvw
更新直接覆盖文件就行

**Comment by louyongjiu** [comment]
建议更新到readme文档 ，方便大家下载

**Comment by zhzLuke96** [comment]
> 建议更新到readme文档 ，方便大家下载

已加入 readme

同时开了个 discussion： https://github.com/lenML/ChatTTS-Forge/discussions/65
