### ISSUE TITLE
[BUG:WebUI] 

### ISSUE THREAD

**Issue by WangLaoShi** [lenML/ChatTTS-Forge#71]
### 阅读 README.md 和 dependencies.md

- [X] 我已经阅读过 README.md 和 dependencies.md 文件

### 检索 issue 和 discussion

- [X] 我已经确认之前没有 issue 或 discussion 涉及此 BUG

### 检查 Forge 版本

- [X] 我已经确认问题发生在最新代码或稳定版本中

### Forge Commit 或者 Tag

123

### Python 版本

3.10

### PyTorch 版本

1

### 操作系统信息

Windows

### BUG 描述

生成的融合声音如何上传，目前报Bug

### 复现步骤

![image](https://github.com/lenML/ChatTTS-Forge/assets/13606490/8c810740-1e85-4476-9003-1070adbedf71)

融合的文件如下

[tmp2uqf2z_1.zip](https://github.com/user-attachments/files/15957128/tmp2uqf2z_1.zip)

### 期望结果

可以实现声音的上传和使用。

### 实际结果

无效，报错

### 错误信息

```shell
File "C:\Users\win10\.conda\envs\ChatTTS\Lib\site-packages\anyio\to_thread.py", line 56, 
in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\win10\.conda\envs\ChatTTS\Lib\site-packages\anyio\_backends\_asyncio.py", 
line 2177, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\Users\win10\.conda\envs\ChatTTS\Lib\site-packages\anyio\_backends\_asyncio.py", 
line 859, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\win10\.conda\envs\ChatTTS\Lib\site-packages\gradio\utils.py", line 832, in
 wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\win10\.conda\envs\ChatTTS\Lib\site-packages\gradio\utils.py", line 832, in
 wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\win10\Documents\GitHub\ChatTTS-Forge\modules\webui\webui_utils.py", line 2
21, in tts_generate
    raise gr.Error("Speaker file is not supported")
gradio.exceptions.Error: 'Speaker file is not supported'
```

**Comment by zhzLuke96** [comment]
fixed e7b759f7765627a768b2feaf932e39b827137346

**Comment by zhzLuke96** [comment]
> > fixed [e7b759f](https://github.com/lenML/ChatTTS-Forge/commit/e7b759f7765627a768b2feaf932e39b827137346)
> 
> 上传不报错了。但是上传的声音无法找到。如何查找呢。

不清楚你说的上传声音无法找到是什么意思？

我估计你理解错了，webui中所有功能都是不会向系统写入数据的，所以这里的上传之后只会留在 webui 中，也就是内存中

如果你想向系统中添加 speaker ，将 `.pt` 文件放到 `/data/speakers` 中即可
