### ISSUE TITLE
[ISSUE] 微调效果问题

### ISSUE THREAD

**Issue by wangqun888** [lenML/ChatTTS-Forge#73]
### 阅读 README.md 和 dependencies.md

- [X] 我已经阅读过 README.md 和 dependencies.md 文件

### 检索 issue 和 discussion

- [X] 我已经确认之前没有 issue 或 discussion 涉及此 BUG

### 检查 Forge 版本

- [X] 我已经确认问题发生在最新代码或稳定版本中

### 你的issues

我使用了大概4分钟的wav语音，切分了45段每段大概5-6秒进行了微调，但是效果感觉不太好。使用的微调参数如下图
<img width="1177" alt="image" src="https://github.com/lenML/ChatTTS-Forge/assets/89631435/50ceeb91-2de4-4870-85a0-e9b866a06d66">
loss一直不收敛，不知道是哪里出了问题，还请大神帮忙看看。谢谢～

**Comment by zhzLuke96** [comment]
因为官方没有完全开源权重，所以这个微调脚本只是属于实验性质的
目前无法clone，只能 `微调` embedding

还有，其实是在收敛的，text_loss 降了 （mse audio 因为没有 encoder 权重所以几乎随机）

**Comment by zhzLuke96** [comment]
可能相关的issues https://github.com/2noise/ChatTTS/issues/369

**Comment by wangqun888** [comment]
谢谢大神😊
