### ISSUE TITLE
[BUG:API] Stream的API生成的音频会有固定的噪声，一顿一顿的声音

### ISSUE THREAD

**Issue by LiuKai22** [lenML/ChatTTS-Forge#78]
### 阅读 README.md 和 dependencies.md

- [X] 我已经阅读过 README.md 和 dependencies.md 文件

### 检索 issue 和 discussion

- [X] 我已经确认之前没有 issue 或 discussion 涉及此 BUG

### 检查 Forge 版本

- [X] 我已经确认问题发生在最新代码或稳定版本中

### Forge Commit 或者 Tag

main

### Python 版本

3.10

### PyTorch 版本

2.3.1

### 操作系统信息

Ubuntu22.04

### BUG 描述

Stream的API生成的音频会有固定的噪声，一顿一顿的声音

### BUG 端点

/v1/tts

### 复现参数

{ 'text': '中华美食，作为世界饮食文化的瑰宝，以其丰富的种类、独特的风味和精湛的烹饪技艺而闻名于世。中国地大物博，各地区的饮食习惯和烹饪方法各具特色，形成了独树一帜的美食体系。从北方的京鲁菜、东北菜，到南方的粤菜、闽菜，无不展现出中华美食的多样性。' } 

### 期望结果

和非流式输出的音频一样的结果。

### 实际结果

会有固定的噪声，一顿一顿的声音，不自然，会有音频拼接的端点

**Comment by LiuKai22** [comment]
https://github.com/lenML/ChatTTS-Forge/assets/86814635/70662288-51c2-4ecb-882a-2e2e809a1d21

上传一段流式生成的音频片段，供参考。
github似乎不支持MP3文件上传，请下载后改后缀到.mp3

**Comment by zhzLuke96** [comment]
duplicate https://github.com/lenML/ChatTTS-Forge/issues/70
