### ISSUE TITLE
[BUG:WebUI] 每次运行脚本打印出来的日志都是相同的错误

### ISSUE THREAD

**Issue by cpken** [lenML/ChatTTS-Forge#80]
### 阅读 README.md 和 dependencies.md

- [X] 我已经阅读过 README.md 和 dependencies.md 文件

### 检索 issue 和 discussion

- [X] 我已经确认之前没有 issue 或 discussion 涉及此 BUG

### 检查 Forge 版本

- [X] 我已经确认问题发生在最新代码或稳定版本中

### Forge Commit 或者 Tag

无

### Python 版本

3.11

### PyTorch 版本

2.3.1+cu121

### 操作系统信息

ubuntu 22.04.1

### BUG 描述

执行脚本：

```python
python webui.py
```

命令窗口都会有错误提示。

### 复现步骤

```python
python webui.py
```

### 期望结果

无此提示

### 实际结果

无错误提示

### 错误信息

```shell
错误提示：


fatal: 不是 git 仓库（或者直至挂载点 /media/data 的任何父目录）
停止在文件系统边界（未设置 GIT_DISCOVERY_ACROSS_FILESYSTEM）。
fatal: 不是 git 仓库（或者直至挂载点 /media/data 的任何父目录）
停止在文件系统边界（未设置 GIT_DISCOVERY_ACROSS_FILESYSTEM）。
fatal: 不是 git 仓库（或者直至挂载点 /media/data 的任何父目录）
停止在文件系统边界（未设置 GIT_DISCOVERY_ACROSS_FILESYSTEM）。
```
```

**Comment by zhzLuke96** [comment]
这是完整报错log吗？会影响webui启动吗？

这里应该只是尝试获取 forge commit 而已，报错不影响程序运行

建议尽量保留 .git 以方便 固定/回滚 版本，比如 [tags](https://github.com/lenML/ChatTTS-Forge/tags) 中的版本，如果你不保留 git 信息可能难以排查具体问题发生的位置

**Comment by cpken** [comment]
是完整报错 log，不影响 webui 启动。感谢。
