### ISSUE TITLE
关于openai api格式接口问题

### ISSUE THREAD

**Issue by zhy844694805** [lenML/ChatTTS-Forge#9]
[您项目里的文档里](http://localhost:8000/docs)写的是OpenAI 风格 API: /v1/openai/audio/speech 提供类似 OpenAI 的语音生成接口。 
但是官方文档里的格式为 https://api.openai.com/v1/audio/speech \ 

报错信息:
INFO:     192.168.1.188:61456 - "POST /v1/audio/speech HTTP/1.1" 404 Not Found
INFO:     192.168.1.188:61450 - "POST /v1/openai/audio/speech HTTP/1.1" 200 OK
接口填写的模型和音色：
 "model": "chattts-4w",
  "voice": "female2",

**Comment by zhzLuke96** [comment]
fixed 3bf349e274d8ab343688d2d76bd59edd29c742ed

顺带一提，readme 中增加了使用curl测试接口的示例，可用关注下

**Comment by zhy844694805** [comment]
感谢您的付出
