### ISSUE TITLE
我使用web ui通过mmsl生成语音时，发现示例中的[BUG:WebUI] <speak version="0.1">     <voice spk="Bob" seed="42" style="narration-relaxed">         使用 break 标签将会简单的 [lbreak]                  <break time="500" />          插入一段空白到生成结果中 [lbreak]     </voice> </speak>转换时会出现错误。

### ISSUE THREAD

**Issue by Zuo-Cheng** [lenML/ChatTTS-Forge#95]
### 阅读 README.md 和 dependencies.md

- [X] 我已经阅读过 README.md 和 dependencies.md 文件

### 检索 issue 和 discussion

- [X] 我已经确认之前没有 issue 或 discussion 涉及此 BUG

### 检查 Forge 版本

- [X] 我已经确认问题发生在最新代码或稳定版本中

### Forge Commit 或者 Tag

1

### Python 版本

1

### PyTorch 版本

1

### 操作系统信息

你的线上案例

### 浏览器信息

webui

### BUG 描述

使用MMSL功能转语音：
<speak version="0.1">
    <voice spk="Bob" seed="42" style="narration-relaxed">
        使用 break 标签将会简单的 [lbreak]
        
        <break time="500" />

        插入一段空白到生成结果中 [lbreak]
    </voice>
</speak>

### 复现步骤

使用MMSL功能转语音：
<speak version="0.1">
    <voice spk="Bob" seed="42" style="narration-relaxed">
        使用 break 标签将会简单的 [lbreak]
        
        <break time="500" />

        插入一段空白到生成结果中 [lbreak]
    </voice>
</speak>

### 期望结果

生成语音成功

### 实际结果

生成报错

### 错误信息

```shell
111
```

**Comment by zhzLuke96** [comment]
无法复现
